### ISSUE TITLE
Lab2: Better match between screenshots and step-by-step instructions

### ISSUE THREAD

**Issue by NFGodoy** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#15] opened 2020-08-30 06:09 UTC
# Module: 02
#### Step: 03

It asks the learner to leave the defaults for the IPv4 address space which is 10.0.0.0/16 and not as per screenshot. So 2 options: (a) replace the screenshot or (b) include an instruction asking the learner to configure as displayed. Same for the default subnet. All that is explicitly asked for is to include Microsoft.Sql in the Services Endpoints, NOT changing the Subnet address range from the default 10.0.0.0/24

**Comment by kalendelaney** [comment] 2020-09-08 22:36
This is a duplicate of an earlier reported issue.

**Closed by kalendelaney** 2020-09-08 22:36 UTC
