### ISSUE TITLE
Missing image in Lab3 Exerc 2 Task 1 Step 10

### ISSUE THREAD

**Issue by NFGodoy** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#17] opened 2020-09-03 10:49 UTC
# Module: 03
#### Step: 10

10. Navigate back to the query tab you opened in step 4, and type ROLLBACK TRANSACTION on the line below the query. Highlight ROLLBACK TRANSACTION and execute the command by clicking.

![Picture 1](../images/dp-3300-module-44-lab-13.png)

My suggestion is to just say "by clicking the Execute button" and skip adding a screenshot in that step.

**Comment by kalendelaney** [comment] 2020-09-25 19:52
This is in Lab 4. It's very helpful when you can specify example where the problem is. Module, Exercise, Task and Step numbers. (Not all exercises have separate tasks with numbers.) 

I'm not seeing a missing image, but this was fixed by just removing 'by clicking' so the sentence ends with 'and execute the command.'

**Closed** 2020-09-25 20:03 UTC
